export class LangBundle {
    static MSG: any = {
        "en": {
            HOME: 'Home',
            EXPORT: 'Export',
            REPORTS: 'Reports',
            SETTINGS: 'Settings',
            ARABIC : 'Arabic',
            Choose_your_location : 'Choose your location',
            D_and_K : 'Dammam & Khobar',
            Jubail : 'Jubail',
            use_current_loc : 'USE MY CURRENT LOCATION',
            plan_your_event : 'Plan your event',
            trending : 'Trending',
            make_ur_own : 'Make Your Own',
            pro_event_planner : 'Professional Event Planner',
            categories : 'Categories',
            category : 'Category',
            subcategory : 'Subcategory',
            subcategories : 'Subcategories',
            Products : 'Products',
            Services : 'Services',
            sort : 'Sort By',
            Stores : 'Stores',
            Loginprofile : 'Please login to view your account.',
            Logincart: 'Please login to view your cart.',
            Loginwish: 'Please login to view your wishlist.',
            wishlist : 'Wishlist',
            login : 'Log In',
            email : 'Email',
            pass : 'Password',
            remember : 'Remember me',
            done : 'Done',
            noaccount : "Don't have an account?",
            signup : 'Sign up',
            forgot : 'Forgot your password?',
            account : 'Account',
            myaccount : 'My account',
            myorders : 'My orders',
            notifications : 'Notifications',
            myprofile : 'My Profile',
            location : 'Location',
            mychat : 'My Chat',
            contactus : 'Contact Us',
            history : 'History',
            changepass : 'Change Password',
            logout : 'Logout',
            indiv_planner : 'Individual Planners',
            event_company : 'Event Organizing Companies',
            no_results : 'No results found.',
            description : 'Description',
            ordernow : 'Order Now',
            chat_with_us : 'Chat with us',
            price : 'Price',
            vendor : 'Vendor',
            name : 'Name',
            phone_number : 'Phone Number',
            confirm_pass : 'Confirm Password',
            gender : 'Gender', 
            male : 'Male',
            female : 'Female',
            join : 'Join',
            terms_n_cond : 'Terms & Conditions',
            Iagree : 'I agree'


        },
        "ar":
        {
            HOME: 'الرئيسية',
            REPORTS: 'التقارير',
            EXPORT: 'Export',
            PROFILE: 'الملف الشخصي',
            SETTINGS: 'الإعدادات',
            ARABIC : 'عربى',
            Choose_your_location : 'ااختر موق',
            D_and_K : 'الدمام و الخبر',
            Jubail : 'الجبيل',
            use_current_loc : 'استخدام موقعي الحالي',
            plan_your_event :'خطط لحدثك',
            trending : 'الشائع',
            make_ur_own : 'اصنع خاصتك',
            pro_event_planner : 'المهنية مخطط الحدث',
            categories : 'الاقسام',
            category : 'الفئة',
            subcategory : 'فرعية',
            subcategories : 'الفئات الفرعية',
            Products : 'منتجات',
            Services : 'خدمات',
            sort : 'ترتيب حسب',
            Stores : 'مخازن',
            Loginprofile : 'الرجاء تسجيل الدخول لعرض حسابك.',
            Logincart: 'الرجاء تسجيل الدخول لعرض سلة التسوق.',
            Loginwish: 'الرجاء تسجيل الدخول لعرض قائمة الأمنيات.',
            wishlist : 'الأماني',
            login : 'تسجيل الدخول',
            email : 'البريد الإلكتروني',
            pass : 'كلمه السر',
            remember : 'تذكرنى',
            done : 'فعله',
            noaccount : 'ليس لديك حساب؟',
            signup : 'سجل',
            forgot : 'نسيت رقمك السري؟',
            account : 'الحساب',
            myaccount : 'حسابي',
            myorders : 'تتبع طلبي',
            notifications: 'إخطارات',
            myprofile : 'ملفي',
            location : 'موقعك',
            mychat : 'دردشة',
            contactus : 'اتصل بنا',
            history : 'التاريخ',
            changepass : 'تغيير كلمة السر',
            logout : 'الخروج',
            indiv_planner : 'المخططون الأفراد',
            event_company : 'الشركات تنظيم الحدث',
            no_results : 'لا توجد نتائج',
            description : 'وصف',
            ordernow : 'اطلب الان',
            chat_with_us : 'دردش معنا',
            price : "السعر",
            vendor : 'بائع',
            name : 'اسم',
            phone_number : 'رقم الهاتف',
            confirm_pass : 'تأكيد كلمة المرور',
            gender : 'جنس',
            male : 'الذكر',
            female : 'إناثا',
            join : 'انضم',
            terms_n_cond : 'البنود و الظروف',
            Iagree : 'أنا أتفق'
            

        }
    };
}